{ pkgs, ... }:

{
  # NOTE: Colors used to live in `settings` below (static, rebuild-time
  # only). Starship's config is now generated by Matugen instead
  # (~/.config/matugen/templates/starship.toml -> ~/.config/starship.toml,
  # see ../style/matugen.nix), so it re-themes itself along with your
  # terminal every time the wallpaper changes — no `settings` block here
  # to avoid two systems fighting over the same file.
  programs.starship = {
    enable = true;
    enableBashIntegration = true;
    enableZshIntegration = true;
    enableFishIntegration = true;
  };
}
